/**
 * What a block state property *means*, and when it changed.
 *
 * ## Why this exists
 *
 * `block_states.ts` knows which properties a block has and what values they may
 * take. That is enough to validate an edit and enough to fill a dropdown, and
 * it is not enough to *choose*. `signal_fire` and `lit` are both booleans on a
 * campfire; nothing in that table says one makes a column of smoke and the
 * other decides whether the fire is burning at all.
 *
 * The gap showed up as a shape of bug rather than as a missing feature. A model
 * driving this app over MCP has to know a block's states before it can name
 * them, so it guessed -- and a guess that is merely *absent* is invisible here,
 * because nothing in this codebase validates a property name and the game fills
 * in whatever the file left out. `describe_block` in `agent/tools.ts` is what
 * closes that, and this is what it reads.
 *
 * ## Keyed by property, not by block
 *
 * ```
 * resources/block_properties.json   the prose, with provenance  <- .claude/skills/mc-blockproperties
 * scripts/gen-block-properties.mjs  JSON -> the table
 * src/shared/block_properties.ts    this file
 * ```
 *
 * 1197 blocks carry 93 distinct property names between them, in 121 distinct
 * forms. Keyed by block, `facing` would be described 335 times and the 335
 * copies would drift; keyed by name alone, a fence and a wall would have to
 * share one sentence about `north` while the game gives them different *types*.
 *
 * So the key is the pair: the name, and the exact set of values it takes. That
 * is not a compromise between the two -- it is the distinction the game
 * actually makes, and the one this app has been bitten by. A wall's `north` is
 * `none|low|tall` and a fence's is `true|false`; code testing for `"true"` does
 * not fail on a wall, it silently reads every connection as absent.
 *
 * ## What is not decided here
 *
 * The legal values and the defaults. Those are `block_states.ts`, generated
 * from the game's own registry, and this file only *names* a value set in order
 * to say which form it is describing. The generator refuses a row naming a
 * combination the registry does not have, which is what stops this file
 * inventing a property rather than describing one.
 *
 * The trust rule differs from its sibling's for the same reason. A wrong
 * property name is mechanically detectable and `mc-blockstates` leans on that;
 * a wrong *sentence* is not detectable by any check this repo could run, so
 * `mc-blockproperties` buys trust by corroboration instead -- which is the rule
 * `mc-versions` applies to history, arrived at from the other direction.
 */

/** One version at which a property changed, and what changed. */
export interface PropertyNote {
  /** The Minecraft version, as the wiki names it. */
  readonly version: string;
  readonly note: string;
}

/** What one property means, in one of the forms it takes. */
export interface PropertyDoc {
  /**
   * The exact value set this row describes.
   *
   * Present so a lookup can tell a fence's `north` from a wall's, and so the
   * generator can refuse a row the game's registry does not corroborate.
   */
  readonly values: readonly string[];
  readonly description: string;
  readonly versions?: readonly PropertyNote[];
  /** Pages beyond the ones in the JSON's `_source`, where a row needed one. */
  readonly sources?: readonly string[];
}

// --- generated by scripts/gen-block-properties.mjs -- do not edit below -----

const PROPERTY_DOCS: Readonly<Record<string, readonly PropertyDoc[]>> = {
  "age": [
    {
      values: ["0", "1"],
      description: "Whether the plant has taken its first growth step. Bamboo thickens at 1; a torchflower crop uses it as the middle of its three stages.",
    },
    {
      values: ["0", "1", "2"],
      description: "How far the cocoa pod has ripened. 2 is fully grown.",
    },
    {
      values: ["0", "1", "2", "3"],
      description: "How far this plant has grown, or how far a block has progressed towards its next state. 3 is the last stage: ripe nether wart, fully thickened frosted ice.",
    },
    {
      values: ["0", "1", "2", "3", "4"],
      description: "How far this plant has grown. A mangrove propagule is ready to be planted at 4; a pitcher crop is ready to harvest.",
    },
    {
      values: ["0", "1", "2", "3", "4", "5"],
      description: "How far a chorus flower has grown. It dies and turns to a dead flower at 5.",
    },
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7"],
      description: "How far a crop has grown. 7 is fully grown and ready to harvest; a stem at 7 is ready to grow its fruit. Wheat, carrots, potatoes and both stems use this range.",
    },
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"],
      description: "For cactus and sugar cane, how tall the plant has grown before it adds a block; for fire, how long it has been burning. The two are unrelated mechanics that happen to share a range.",
    },
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"],
      description: "How long a hanging or climbing vine has grown. The plant stops extending once it reaches 25.",
    },
  ],
  "attached": [
    {
      values: ["true", "false"],
      description: "For a tripwire or its hook, whether the string is strung between two hooks; for a hanging sign, whether it hangs from a bar rather than from chains.",
    },
  ],
  "attachment": [
    {
      values: ["floor", "ceiling", "single_wall", "double_wall"],
      description: "How the bell is hung: standing on the floor, hanging from the ceiling, bolted to one wall, or slung between two.",
    },
  ],
  "axis": [
    {
      values: ["x", "y", "z"],
      description: "Which way the block is turned. `y` is upright, `x` runs east-west and `z` runs north-south. Logs, pillars and bone blocks use it instead of `facing` because they look the same from either end.",
    },
    {
      values: ["x", "z"],
      description: "Which way the nether portal's plane runs. It is always upright, so only the two horizontal axes exist.",
    },
  ],
  "berries": [
    {
      values: ["true", "false"],
      description: "Whether this section of cave vines is carrying glow berries.",
    },
  ],
  "bites": [
    {
      values: ["0", "1", "2", "3", "4", "5", "6"],
      description: "The number of bites taken from the cake. At 7 the block is gone, so 6 is the last state that exists.",
    },
  ],
  "bloom": [
    {
      values: ["true", "false"],
      description: "Whether the sculk catalyst is blooming, which it does for a moment after something dies nearby.",
    },
  ],
  "bottom": [
    {
      values: ["true", "false"],
      description: "For scaffolding, whether it is floating and drawn with its lower bracing; for a pale moss carpet, whether it shows the hanging vine underneath.",
    },
  ],
  "can_summon": [
    {
      values: ["true", "false"],
      description: "Whether this shrieker can call a warden. Only naturally generated ones can.",
    },
  ],
  "candles": [
    {
      values: ["1", "2", "3", "4"],
      description: "How many candles are in this block.",
    },
  ],
  "charges": [
    {
      values: ["0", "1", "2", "3", "4"],
      description: "How many uses the respawn anchor has left.",
    },
  ],
  "conditional": [
    {
      values: ["true", "false"],
      description: "Whether the command block only runs when the one behind it succeeded.",
    },
  ],
  "copper_golem_pose": [
    {
      values: ["standing", "sitting", "running", "star"],
      description: "Which pose the copper golem statue is frozen in.",
    },
  ],
  "cracked": [
    {
      values: ["true", "false"],
      description: "Whether the decorated pot is cracked, which is what makes it shatter rather than drop.",
    },
  ],
  "crafting": [
    {
      values: ["true", "false"],
      description: "Whether the crafter is mid-craft.",
    },
  ],
  "creaking_heart_state": [
    {
      values: ["uprooted", "dormant", "awake"],
      description: "Whether the creaking heart is correctly built into pale oak, and whether its creaking is out.",
    },
  ],
  "delay": [
    {
      values: ["1", "2", "3", "4"],
      description: "How many redstone ticks the repeater waits before passing a signal on.",
    },
  ],
  "disarmed": [
    {
      values: ["true", "false"],
      description: "Whether the tripwire has been cut with shears, so it no longer fires.",
    },
  ],
  "distance": [
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7"],
      description: "How far this scaffolding is from a block that supports it. Scaffolding at 7 with nothing under it falls.",
    },
    {
      values: ["1", "2", "3", "4", "5", "6", "7"],
      description: "How far these leaves are from the nearest log. Leaves further than 6 away decay, which is what `persistent` overrides.",
    },
  ],
  "down": [
    {
      values: ["true", "false"],
      description: "Whether the block continues downwards -- the same question as `up`, asked of the block below.",
    },
  ],
  "drag": [
    {
      values: ["true", "false"],
      description: "Whether the bubble column pulls things down (a whirlpool over magma) rather than pushing them up.",
    },
  ],
  "dusted": [
    {
      values: ["0", "1", "2", "3"],
      description: "How far a suspicious block has been brushed. The item comes out at 3.",
    },
  ],
  "east": [
    {
      values: ["none", "low", "tall"],
      description: "How the wall extends towards the east: not at all, a low arm, or a tall one that reaches the top of the centre post.",
      versions: [
        { version: "1.16", note: "Changed from true/false to none/low/tall in snapshot 20w06a, when walls stopped leaving gaps where they stacked. Code that tests for the string \"true\" does not fail on a modern wall -- it silently reads every connection as absent." },
      ],
      sources: ["https://minecraft.wiki/w/Wall"],
    },
    {
      values: ["true", "false"],
      description: "Whether the block joins on to whatever is to its east. Fences, panes, iron bars, chorus plants, vines, glow lichen and mushroom blocks all use it; on a mushroom block it decides whether that face wears the cap texture rather than the stem.",
    },
    {
      values: ["up", "side", "none"],
      description: "How the redstone dust runs east: `side` is flat along the ground, `up` climbs the block on that side, `none` is no connection.",
    },
  ],
  "eggs": [
    {
      values: ["1", "2", "3", "4"],
      description: "How many eggs are in this block.",
    },
  ],
  "enabled": [
    {
      values: ["true", "false"],
      description: "Whether the hopper is moving items. A hopper receiving a redstone signal is disabled.",
    },
  ],
  "extended": [
    {
      values: ["true", "false"],
      description: "Whether the piston is pushed out.",
    },
  ],
  "eye": [
    {
      values: ["true", "false"],
      description: "Whether the end portal frame holds an eye of ender.",
    },
  ],
  "face": [
    {
      values: ["floor", "wall", "ceiling"],
      description: "Which surface the block is attached to. With `facing`, this is what separates a button on the floor pointing north from one on the north wall.",
    },
  ],
  "facing": [
    {
      values: ["down", "north", "south", "west", "east"],
      description: "Which way the hopper's spout points. Every direction but `up`, because a hopper cannot push items upwards.",
    },
    {
      values: ["north", "east", "south", "west", "up", "down"],
      description: "Which way the block's front faces, including straight up and straight down. This is the range for the blocks that can be aimed at the ceiling or the floor: droppers, dispensers, observers, barrels, shulker boxes, amethyst clusters and the pistons.",
    },
    {
      values: ["north", "south", "west", "east"],
      description: "Which way the block's front faces, horizontally. Which way counts as the front differs by block: a staircase's steps rise away from its `facing`, while a wall torch or a ladder faces *out* of the wall it is attached to.",
    },
  ],
  "flower_amount": [
    {
      values: ["1", "2", "3", "4"],
      description: "How many flowers are in this group. Each one is drawn as its own small plate at its own height, so a patch does not read as a grid.",
    },
  ],
  "half": [
    {
      values: ["top", "bottom"],
      description: "Which half of the cell the block occupies. A staircase or a trapdoor placed against the upper part of a block sits at the top of its cell and is drawn upside down.",
    },
    {
      values: ["upper", "lower"],
      description: "Which half of a two-block-tall block this is: a door, a tall flower, a large fern, a sunflower. Both halves have to exist and agree, or the block breaks the moment anything updates it.",
    },
  ],
  "hanging": [
    {
      values: ["true", "false"],
      description: "Whether the lantern hangs from the block above rather than standing on the block below.",
    },
  ],
  "has_book": [
    {
      values: ["true", "false"],
      description: "Whether the lectern is holding a book.",
    },
  ],
  "has_bottle_0": [
    {
      values: ["true", "false"],
      description: "Whether the brewing stand's bottle slot 0 is holding a bottle. The three slots are three separate properties, and each one is drawn.",
    },
  ],
  "has_bottle_1": [
    {
      values: ["true", "false"],
      description: "Whether the brewing stand's bottle slot 1 is holding a bottle. The three slots are three separate properties, and each one is drawn.",
    },
  ],
  "has_bottle_2": [
    {
      values: ["true", "false"],
      description: "Whether the brewing stand's bottle slot 2 is holding a bottle. The three slots are three separate properties, and each one is drawn.",
    },
  ],
  "has_record": [
    {
      values: ["true", "false"],
      description: "Whether the jukebox is holding a music disc.",
    },
  ],
  "hatch": [
    {
      values: ["0", "1", "2"],
      description: "How close the eggs are to hatching. It counts up, and the eggs hatch after 2.",
    },
  ],
  "hinge": [
    {
      values: ["left", "right"],
      description: "Which side of the door the hinge is on, seen from the side the door faces. It decides which way the door swings and which way round the texture is drawn. The game fixes it at the moment of placement, from the neighbouring blocks and from where on the block the click landed, and never revisits it.",
    },
  ],
  "honey_level": [
    {
      values: ["0", "1", "2", "3", "4", "5"],
      description: "How full of honey the hive is. It can be harvested at 5.",
    },
  ],
  "hydration": [
    {
      values: ["0", "1", "2", "3"],
      description: "How wet the dried ghast is. It rehydrates in water and dries out in the air.",
    },
  ],
  "in_wall": [
    {
      values: ["true", "false"],
      description: "Whether the fence gate sits three pixels lower, so it lines up with the wall it is set into rather than with a fence.",
    },
  ],
  "instrument": [
    {
      values: ["harp", "basedrum", "snare", "hat", "bass", "flute", "bell", "guitar", "chime", "xylophone", "iron_xylophone", "cow_bell", "didgeridoo", "bit", "banjo", "pling", "trumpet", "trumpet_exposed", "trumpet_oxidized", "trumpet_weathered", "zombie", "skeleton", "creeper", "dragon", "wither_skeleton", "piglin", "custom_head"],
      description: "Which instrument the note block plays. The game sets it from the block underneath, so it is not usually chosen by hand.",
    },
  ],
  "inverted": [
    {
      values: ["true", "false"],
      description: "Whether the daylight detector measures darkness instead of light.",
    },
  ],
  "layers": [
    {
      values: ["1", "2", "3", "4", "5", "6", "7", "8"],
      description: "How deep the snow is, in eighths of a block. At 8 it is a full block high.",
    },
  ],
  "leaves": [
    {
      values: ["none", "small", "large"],
      description: "How big the leaves are on this bamboo. A stalk grows small leaves and then large ones at its top.",
    },
  ],
  "level": [
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7", "8"],
      description: "How full the composter is. It can be emptied at 8.",
    },
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"],
      description: "For water and lava, how much of the cell the fluid fills: 0 is a source and higher numbers are shallower, with 8 and above meaning the fluid is falling. For a light block it is the brightness it emits.",
    },
    {
      values: ["1", "2", "3"],
      description: "How full the cauldron is, in thirds.",
    },
  ],
  "lit": [
    {
      values: ["true", "false"],
      description: "Whether the block is burning, lit or switched on: a furnace smelting, a campfire alight, a redstone lamp glowing, a candle burning.",
      versions: [
        { version: "1.13", note: "Before the Flattening a lit block was a different block id -- furnace 61 against lit furnace 62, redstone lamp 123 against 124. Files from those versions carry the numeric pair, not this property." },
      ],
    },
  ],
  "locked": [
    {
      values: ["true", "false"],
      description: "Whether the repeater is held in its current state by a signal from the side.",
    },
  ],
  "mode": [
    {
      values: ["compare", "subtract"],
      description: "Which way the comparator works: `compare` passes the back signal through unless a side beats it, `subtract` takes the strongest side signal away from it.",
    },
    {
      values: ["save", "load", "corner", "data"],
      description: "Which job the structure block is doing.",
    },
    {
      values: ["start", "log", "fail", "accept"],
      description: "Which job the test block is doing.",
    },
  ],
  "moisture": [
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7"],
      description: "How wet the farmland is. 7 is fully hydrated; farmland at 0 with nothing planted on it turns back into dirt.",
    },
  ],
  "natural": [
    {
      values: ["true", "false"],
      description: "Whether the creaking heart was generated with the world rather than built, which is what lets it spawn a creaking.",
    },
  ],
  "north": [
    {
      values: ["none", "low", "tall"],
      description: "How the wall extends towards the north: not at all, a low arm, or a tall one that reaches the top of the centre post.",
      versions: [
        { version: "1.16", note: "Changed from true/false to none/low/tall in snapshot 20w06a, when walls stopped leaving gaps where they stacked. Code that tests for the string \"true\" does not fail on a modern wall -- it silently reads every connection as absent." },
      ],
      sources: ["https://minecraft.wiki/w/Wall"],
    },
    {
      values: ["true", "false"],
      description: "Whether the block joins on to whatever is to its north. Fences, panes, iron bars, chorus plants, vines, glow lichen and mushroom blocks all use it; on a mushroom block it decides whether that face wears the cap texture rather than the stem.",
    },
    {
      values: ["up", "side", "none"],
      description: "How the redstone dust runs north: `side` is flat along the ground, `up` climbs the block on that side, `none` is no connection.",
    },
  ],
  "note": [
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24"],
      description: "Which of twenty-five notes the note block plays, counting up two octaves from F#.",
    },
  ],
  "occupied": [
    {
      values: ["true", "false"],
      description: "Whether somebody is already sleeping in this bed.",
    },
  ],
  "ominous": [
    {
      values: ["true", "false"],
      description: "Whether the trial spawner or vault is in its ominous form.",
    },
  ],
  "open": [
    {
      values: ["true", "false"],
      description: "Whether the door, trapdoor, fence gate or barrel is open.",
    },
  ],
  "orientation": [
    {
      values: ["down_east", "down_north", "down_south", "down_west", "up_east", "up_north", "up_south", "up_west", "west_up", "east_up", "north_up", "south_up"],
      description: "Which way the block points, as a pair: the face the output goes to, then which way the block is rolled about that face. Crafters and jigsaws use it because they can be aimed in any of six directions and still turned.",
    },
  ],
  "part": [
    {
      values: ["head", "foot"],
      description: "Which end of the bed this is. A bed is two blocks; a lone foot or head drops as an item as soon as anything updates it.",
    },
  ],
  "persistent": [
    {
      values: ["true", "false"],
      description: "Whether the leaves decay. Leaves placed by a player are persistent and never decay; leaves grown by a tree are not.",
    },
  ],
  "pickles": [
    {
      values: ["1", "2", "3", "4"],
      description: "How many sea pickles are in this block.",
    },
  ],
  "potent_sulfur_state": [
    {
      values: ["dry", "wet", "dormant", "erupting", "continuous"],
      description: "Which state the potent sulfur block is in.",
    },
  ],
  "power": [
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"],
      description: "How strong a redstone signal the block is emitting or carrying. 0 is none and 15 is full strength.",
    },
  ],
  "powered": [
    {
      values: ["true", "false"],
      description: "Whether the block is receiving a redstone signal. On a door, a trapdoor or a fence gate it also means the block is being held open.",
    },
  ],
  "rotation": [
    {
      values: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"],
      description: "Which of sixteen directions a standing sign, banner, head or skull faces. 0 is south and the value increases clockwise seen from above, so 4 is west, 8 is north and 12 is east.",
      versions: [
        { version: "26.1", note: "The default changed from 0 to 8 for signs and banners (snapshot 11), so a block placed in 26.1 or later starts facing north rather than south. minecraft.wiki's Sign page still says the default has always been 0; the game's own data at 26.2 says 8, which is what this app vendors." },
      ],
      sources: ["https://minecraft.wiki/w/Sign"],
    },
  ],
  "sculk_sensor_phase": [
    {
      values: ["inactive", "active", "cooldown"],
      description: "Where the sculk sensor is in its cycle: listening, firing, or waiting before it can fire again.",
    },
  ],
  "segment_amount": [
    {
      values: ["1", "2", "3", "4"],
      description: "How many leaves are in this group of leaf litter, drawn the same way a flowerbed is.",
    },
  ],
  "shape": [
    {
      values: ["north_south", "east_west", "ascending_east", "ascending_west", "ascending_north", "ascending_south"],
      description: "Which way this rail runs, and whether it slopes. Powered, detector and activator rails cannot curve, so they have only the six straight and ascending shapes.",
    },
    {
      values: ["north_south", "east_west", "ascending_east", "ascending_west", "ascending_north", "ascending_south", "south_east", "south_west", "north_west", "north_east"],
      description: "Which way this rail runs. Plain rail is the only one that can curve, which is what the four extra corner shapes are.",
    },
    {
      values: ["straight", "inner_left", "inner_right", "outer_left", "outer_right"],
      description: "How this staircase meets the ones beside it. `straight` is a plain step; the inner and outer shapes are the corner pieces the game derives from the neighbouring stairs. A stored shape is advisory -- the game recomputes it on every neighbour update.",
    },
  ],
  "short": [
    {
      values: ["true", "false"],
      description: "Whether the piston head's arm is drawn four pixels shorter, which it is while the piston is still moving.",
    },
  ],
  "shrieking": [
    {
      values: ["true", "false"],
      description: "Whether the sculk shrieker is shrieking.",
    },
  ],
  "side_chain": [
    {
      values: ["unconnected", "right", "center", "left"],
      description: "Where this shelf sits in a run of them, so the ends and the middle are drawn differently.",
    },
  ],
  "signal_fire": [
    {
      values: ["true", "false"],
      description: "Whether this campfire sends up the tall column of smoke. A campfire lit over a hay bale becomes a signal fire.",
    },
  ],
  "slot_0_occupied": [
    {
      values: ["true", "false"],
      description: "Whether slot 0 of the chiselled bookshelf holds a book. The six slots are six separate properties, and each one is drawn.",
    },
  ],
  "slot_1_occupied": [
    {
      values: ["true", "false"],
      description: "Whether slot 1 of the chiselled bookshelf holds a book. The six slots are six separate properties, and each one is drawn.",
    },
  ],
  "slot_2_occupied": [
    {
      values: ["true", "false"],
      description: "Whether slot 2 of the chiselled bookshelf holds a book. The six slots are six separate properties, and each one is drawn.",
    },
  ],
  "slot_3_occupied": [
    {
      values: ["true", "false"],
      description: "Whether slot 3 of the chiselled bookshelf holds a book. The six slots are six separate properties, and each one is drawn.",
    },
  ],
  "slot_4_occupied": [
    {
      values: ["true", "false"],
      description: "Whether slot 4 of the chiselled bookshelf holds a book. The six slots are six separate properties, and each one is drawn.",
    },
  ],
  "slot_5_occupied": [
    {
      values: ["true", "false"],
      description: "Whether slot 5 of the chiselled bookshelf holds a book. The six slots are six separate properties, and each one is drawn.",
    },
  ],
  "snowy": [
    {
      values: ["true", "false"],
      description: "Whether the block draws its snow-covered side texture. True when snow or a snow block sits directly on top.",
    },
  ],
  "south": [
    {
      values: ["none", "low", "tall"],
      description: "How the wall extends towards the south: not at all, a low arm, or a tall one that reaches the top of the centre post.",
      versions: [
        { version: "1.16", note: "Changed from true/false to none/low/tall in snapshot 20w06a, when walls stopped leaving gaps where they stacked. Code that tests for the string \"true\" does not fail on a modern wall -- it silently reads every connection as absent." },
      ],
      sources: ["https://minecraft.wiki/w/Wall"],
    },
    {
      values: ["true", "false"],
      description: "Whether the block joins on to whatever is to its south. Fences, panes, iron bars, chorus plants, vines, glow lichen and mushroom blocks all use it; on a mushroom block it decides whether that face wears the cap texture rather than the stem.",
    },
    {
      values: ["up", "side", "none"],
      description: "How the redstone dust runs south: `side` is flat along the ground, `up` climbs the block on that side, `none` is no connection.",
    },
  ],
  "stage": [
    {
      values: ["0", "1"],
      description: "Whether a sapling or bamboo has taken its first growth step. A sapling needs two before it becomes a tree.",
    },
  ],
  "thickness": [
    {
      values: ["tip_merge", "tip", "frustum", "middle", "base"],
      description: "Which part of a dripstone column this block is. `tip_merge` is the tip where a stalactite and a stalagmite meet.",
    },
  ],
  "tilt": [
    {
      values: ["none", "unstable", "partial", "full"],
      description: "How far the big dripleaf has tipped under something standing on it. It goes none, unstable, partial, full and then drops whatever is on it.",
    },
  ],
  "tip": [
    {
      values: ["true", "false"],
      description: "Whether this is the bottom block of a strand of pale hanging moss.",
    },
  ],
  "trial_spawner_state": [
    {
      values: ["inactive", "waiting_for_players", "active", "waiting_for_reward_ejection", "ejecting_reward", "cooldown"],
      description: "Where the trial spawner is in its cycle.",
    },
  ],
  "triggered": [
    {
      values: ["true", "false"],
      description: "Whether the block has been set off and is waiting to be reset. Dispensers, droppers and crafters use it so one redstone pulse fires them once.",
    },
  ],
  "type": [
    {
      values: ["normal", "sticky"],
      description: "Which kind of piston this head or moving block belongs to.",
    },
    {
      values: ["single", "left", "right"],
      description: "Whether this chest stands alone or is half of a double chest, and which half. Left and right are seen from the front.",
    },
    {
      values: ["top", "bottom", "double"],
      description: "Which half of the cell the slab fills, or `double` when two slabs have been put in one cell and become a full block. Two matching slabs meeting in one cell make a double slab; they do not stack into two cells.",
    },
  ],
  "unstable": [
    {
      values: ["true", "false"],
      description: "Whether the TNT goes off when it is punched rather than dropping as an item.",
    },
  ],
  "up": [
    {
      values: ["true", "false"],
      description: "Whether the block continues upwards. On a wall this is the centre post, which is drawn whenever the wall is not a plain straight run; on a chorus plant, a vine or glow lichen it is a connection like the four horizontal ones.",
    },
  ],
  "vault_state": [
    {
      values: ["inactive", "active", "unlocking", "ejecting"],
      description: "Where the vault is in its cycle.",
    },
  ],
  "vertical_direction": [
    {
      values: ["up", "down"],
      description: "Which way the dripstone points: `down` is a stalactite hanging from the ceiling, `up` is a stalagmite standing on the floor.",
    },
  ],
  "waterlogged": [
    {
      values: ["true", "false"],
      description: "Whether the cell also holds water. It is how the game floods a block that does not fill its cell -- a fence, a slab, a stair, a sign -- and the block is drawn with water around it.",
    },
  ],
  "west": [
    {
      values: ["none", "low", "tall"],
      description: "How the wall extends towards the west: not at all, a low arm, or a tall one that reaches the top of the centre post.",
      versions: [
        { version: "1.16", note: "Changed from true/false to none/low/tall in snapshot 20w06a, when walls stopped leaving gaps where they stacked. Code that tests for the string \"true\" does not fail on a modern wall -- it silently reads every connection as absent." },
      ],
      sources: ["https://minecraft.wiki/w/Wall"],
    },
    {
      values: ["true", "false"],
      description: "Whether the block joins on to whatever is to its west. Fences, panes, iron bars, chorus plants, vines, glow lichen and mushroom blocks all use it; on a mushroom block it decides whether that face wears the cap texture rather than the stem.",
    },
    {
      values: ["up", "side", "none"],
      description: "How the redstone dust runs west: `side` is flat along the ground, `up` climbs the block on that side, `none` is no connection.",
    },
  ],
};

// --- end generated ---------------------------------------------------------

/**
 * What one property means, in the form this block takes it.
 *
 * `null` when nothing describes it, which is a real answer: an undescribed
 * property is one nobody has looked up yet, and saying so is better than
 * reaching for the nearest row with the same name. That is exactly how a wall's
 * `north` would come to be described as a boolean.
 *
 * The values must match **exactly**, order included. They can only ever come
 * from the same generated registry on both sides, so a mismatch means the two
 * files have drifted apart -- and answering anyway would hide that.
 */
export function describeProperty(
  property: string,
  values: readonly string[],
): PropertyDoc | null {
  const rows = PROPERTY_DOCS[property];
  if (rows === undefined) return null;
  const key = values.join(" ");
  return rows.find((row) => row.values.join(" ") === key) ?? null;
}

/** Every form of a property that carries a description. For the suites. */
export function documentedPropertyCount(): number {
  return Object.values(PROPERTY_DOCS).reduce((total, rows) => total + rows.length, 0);
}

/** Exported so a suite can walk the table against the registry. */
export function documentedProperties(): Readonly<Record<string, readonly PropertyDoc[]>> {
  return PROPERTY_DOCS;
}
