/**
 * Which Litematica schematic version a file is, and which one this app writes.
 *
 * In `shared/` for `mc_versions.ts`'s reason: the format picker has to refuse
 * `.litematic` for 1.13 without importing out of `main/`, and the writer has to
 * enforce the same rule. One answer, mirrored by the UI and enforced by main.
 *
 * ## The `Version` tag is not decoration
 *
 * Litematica reads a file according to what it says it is. Below schematic
 * version 5, **or** below Minecraft DataVersion 1631, it runs the palette
 * through its 1.12-to-1.13.2 conversion -- so a modern palette under an old
 * label does not fail, it comes back converted. That is the shape of bug this
 * app already shipped once with Sponge v2 and v3 spelling one tag `Offset` and
 * not meaning the same vector by it: silent in both directions, and discovered
 * a long way from here.
 *
 * So the floor is **1.13.2, not 1.13**, and the difference is not pedantry.
 * 1.13 is DataVersion 1519, which is below 1631, and Litematica would convert
 * a file claiming it. The app's own era rule calls 1.13 flat and is right about
 * Sponge; this container simply starts one release later.
 *
 * ## Block storage stopped moving at 5
 *
 * Versions 6 and 7 change what goes *inside* an entity or a block entity --
 * 6 came with a sleeping-entity position fix, 7 with 1.20.5's data components
 * -- and this app carries that NBT verbatim, exactly as it does for Sponge. The
 * palette, the packed longs and `Position`/`Size` have been the same since 5,
 * which is why one decoder reads all three.
 *
 * What that costs is one rule on the way out: the version written is chosen
 * from the document's own DataVersion. Always 7 would produce files Litematica
 * below 1.20.6 refuses outright; always 6 would put component-shaped item NBT
 * under a label that promises the older shape.
 *
 * The rows are looked up rather than remembered, per version of the mod, and
 * `.claude/skills/mc-litematic` is how. `resources/litematica_versions.json`
 * holds them with the branch each constant was read from.
 */

export interface LitematicVersion {
  /** The `Version` tag. */
  readonly version: number;
  /** The `SubVersion` tag written beside it; 0 for an era that wrote none. */
  readonly subVersion: number;
  /** The oldest Minecraft release whose Litematica writes this version. */
  readonly since: string;
  /** That release's DataVersion, which is what a document actually carries. */
  readonly sinceDataVersion: number;
  /** What changed, in one line. */
  readonly note: string;
}

/**
 * Newest first, which is the order `litematicVersionFor` wants: the first row
 * a DataVersion reaches is its answer.
 *
 * Only the versions this app can write are here. 1 to 4 are pre-Flattening and
 * are named in the JSON with what little is known about them, which is not
 * enough to write one and is enough to refuse one by name.
 */
export const LITEMATIC_VERSIONS: readonly LitematicVersion[] = [
  // <<< generated by scripts/gen-litematica-versions.mjs -- do not edit by hand
  { version: 7, subVersion: 1, since: "1.20.5", sinceDataVersion: 3837, note: "Item stacks carry data components. Litematica below 1.20.6 refuses to read it." },
  { version: 6, subVersion: 1, since: "1.18", sinceDataVersion: 2860, note: "SubVersion appears, at 1, after the sleeping-entity position fix." },
  { version: 5, subVersion: 0, since: "1.13.2", sinceDataVersion: 1631, note: "The Flattening. PendingFluidTicks appears. Block storage has not changed since." },
  // >>> end generated
];

/**
 * The oldest schematic version whose block storage is the one decoded here.
 *
 * A file below it is refused by name rather than read as best it can be: its
 * palette is pre-Flattening numeric ids, which is a different decoder and a
 * different table, and guessing would produce a document full of the wrong
 * blocks that looked like a successful load.
 */
export const LITEMATIC_MIN_VERSION = 5;

/** The DataVersion of the oldest release this container can honestly claim. */
export const LITEMATIC_MIN_DATA_VERSION = 1631;

/** How a human says that release. Kept beside the number so a message can name it. */
export const LITEMATIC_MIN_LABEL = "1.13.2";

/**
 * The version to stamp on a file for a document carrying `dataVersion`.
 *
 * Newest row at or below it. A DataVersion older than every row is a caller
 * that got past `litematicCanCarry`, so this returns the oldest row rather than
 * `null` -- the refusal belongs at the edge, and a writer that has been told to
 * go ahead should not have a second opinion.
 */
export function litematicVersionFor(dataVersion: number): LitematicVersion {
  for (const row of LITEMATIC_VERSIONS) {
    if (dataVersion >= row.sinceDataVersion) return row;
  }
  return LITEMATIC_VERSIONS[LITEMATIC_VERSIONS.length - 1];
}

/**
 * Whether a DataVersion can be written as a litematic at all.
 *
 * `null` is false, and deliberately: a litematic must carry a
 * `MinecraftDataVersion`, so a document that names no version has nothing
 * honest to put there. Sponge omits the tag and MCEdit has none; this container
 * has neither escape, and inventing 1631 would tell every reader downstream
 * that a build was cut from a version nobody said it was.
 */
export function litematicCanCarry(dataVersion: number | null): boolean {
  return dataVersion !== null && dataVersion >= LITEMATIC_MIN_DATA_VERSION;
}
